[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ct_tfpnp"
dynamic = ["version"]
description = "TFPnP reproduction for sparse-view CT reconstruction."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
    { name = "Emilia Zabrzanska", email = "eaz21@cam.ac.uk" },
]

dependencies = [
    "numpy<2",
    "torch",
    "torchvision",  
    "matplotlib",
    "scipy",
    "pandas",     
    "tqdm",
]

[project.optional-dependencies]
# pip install -e ".[metrics]"  etc.
metrics = ["piq"]                                  
test = ["pytest"]
docs = ["sphinx>=7.2", "furo", "myst-parser"]

[project.urls]
"Source" = "https://gitlab.developers.cam.ac.uk/phy/data-intensive-science-mphil/assessments/projects/eaz21"

[tool.setuptools_scm]
write_to = "src/ct_tfpnp/version.py"

[tool.setuptools.packages.find]
where = ["src"]

# Keep pytest config here rather than a separate pytest.ini
[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]